Revert "Stop converting Path to str for skimage"
skimage doesn't accept PathLike objects as filenames.
io.imread(p)
OSError: cannot identify image file 'a_path.tiff'

io.imsave(p, im)
ValueError: Images of type float must be between -1 and 1.

This reverts commit cc2f114a7fd9c78aeebc9df62a3bd2cf24452e34.